name: CI/CD Pipeline
#Triggering the Workflow
on:
  push:
    branches:
      - main
#Build Job
jobs:
  build:
    runs-on: ubuntu-latest
    #Checks out the code from the repository
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    #Sets up Python 3.9 environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    #Installs dependencies from requiremnt.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #Executes tests using pytest
    - name: Test with pytest
      run: |
        pytest
    #Builds Docker image
    - name: Build Docker image
      run: |
        docker build -t vehicle-management-system .
    #Logs in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #Pushes Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker tag vehicle-management-system:latest yourdockerhubusername/vehicle-management-system:latest
        docker push yourdockerhubusername/vehicle-management-system:latest

#Deploys the job
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
      run: |
        pip install awsebcli
        eb init -p python-3.8 vehicle-management -r us-west-2
        eb deploy #Deploys to AWS Elastic Beanstalk
